"""Selected-ticket actions; layout is kept separate from workflow orchestration."""
from __future__ import annotations
from PyQt6.QtCore import Qt
from PyQt6.QtWidgets import QFrame, QHBoxLayout, QLabel, QPushButton, QScrollArea, QVBoxLayout, QTabWidget, QWidget, QComboBox, QTextEdit, QLineEdit

def build_inspector(self) -> QWidget:
    panel = QFrame()
    panel.setObjectName("inspector")
    panel.setMinimumWidth(298)
    panel.setMaximumWidth(412)
    layout = QVBoxLayout(panel)
    layout.setContentsMargins(9, 7, 9, 9)
    layout.setSpacing(4)
    top = QHBoxLayout()
    inspector_title = QLabel("Ticket Inspector")
    inspector_title.setObjectName("eyebrow")
    close = QPushButton("×")
    close.setFixedSize(24, 24)
    close.setStyleSheet("padding: 0; font-size: 16px;")
    close.setToolTip("Close inspector")
    close.setAccessibleName("Close inspector")
    close.setProperty("secondary", True)
    close.clicked.connect(self.hide_inspector)
    top.addWidget(inspector_title)
    top.addStretch()
    top.addWidget(close)
    layout.addLayout(top)

    self.ticket_key_label = QLabel("NO TICKET SELECTED")
    self.ticket_key_label.setObjectName("eyebrow")
    self.title = QLabel("Select a ticket")
    self.title.setObjectName("inspectorTitle")
    self.title.setWordWrap(True)
    self.full_detail = QPushButton("Full ticket workspace")
    self.full_detail.setProperty("secondary", True)
    self.full_detail.setToolTip("Open the detailed ticket and local-AI workspace (Ctrl+Shift+R)")
    self.meta = QLabel("")
    self.meta.setObjectName("muted")
    self.meta.setWordWrap(True)
    layout.addWidget(self.ticket_key_label)
    layout.addWidget(self.title)
    layout.addWidget(self.meta)
    layout.addWidget(self.full_detail)

    self.inspector_tabs = QTabWidget()
    self.inspector_tabs.setObjectName("inspectorTabs")
    self.inspector_tabs.setDocumentMode(True)

    work_tab = QWidget()
    work_tab.setObjectName("inspectorTab")
    work_layout = QVBoxLayout(work_tab)
    work_layout.setContentsMargins(7, 7, 7, 7)
    work_layout.setSpacing(4)
    self.reminder_state = QLabel("No reminder")
    self.reminder_state.setObjectName("muted")
    self.work_state = QLabel("No active timer")
    self.work_state.setObjectName("badge")
    self.work_help = QLabel("Local work timer. Starting can also move the ticket to the project’s in-progress status.")
    self.work_help.setObjectName("muted")
    self.work_help.setWordWrap(True)
    work_layout.addWidget(self.work_state)
    work_layout.addWidget(self.work_help)
    work_buttons = QHBoxLayout()
    self.start = QPushButton("Start work")
    self.stop = QPushButton("Stop")
    self.stop.setProperty("secondary", True)
    work_buttons.addWidget(self.start, 2)
    work_buttons.addWidget(self.stop, 1)
    work_layout.addLayout(work_buttons)

    workspace_label = QLabel("TICKET WORKSPACE")
    workspace_label.setObjectName("eyebrow")
    work_layout.addWidget(workspace_label)
    workspace_row = QHBoxLayout()
    self.note = QPushButton("Open note")
    self.note.setProperty("secondary", True)
    self.source_control_button = QPushButton("Source control")
    self.source_control_button.setProperty("secondary", True)
    self.source_control_button.setToolTip("Open this ticket's SVN workspace (Ctrl+Alt+S)")
    workspace_row.addWidget(self.note)
    workspace_row.addWidget(self.source_control_button)
    work_layout.addLayout(workspace_row)
    self.environment_button = QPushButton("Project environment")
    self.environment_button.setProperty("secondary", True)
    self.environment_button.setToolTip("Open saved 検証 / ライブ / ローカル details")
    work_layout.addWidget(self.environment_button)
    patch_row = QHBoxLayout()
    self.make_patch_button = QPushButton("Make patch")
    self.make_patch_button.setProperty("secondary", True)
    self.make_patch_button.setToolTip("Open Source Control with this ticket as the patch context and create the patch")
    self.patches_button = QPushButton("Patches")
    self.patches_button.setProperty("secondary", True)
    self.patches_button.setToolTip("Open this ticket's patch shelf")
    self.patches_button.setEnabled(False)
    patch_row.addWidget(self.make_patch_button)
    patch_row.addWidget(self.patches_button)
    work_layout.addLayout(patch_row)
    work_layout.addStretch()

    backlog_tab = QWidget()
    backlog_tab.setObjectName("inspectorTab")
    backlog_layout = QVBoxLayout(backlog_tab)
    backlog_layout.setContentsMargins(7, 7, 7, 7)
    backlog_layout.setSpacing(4)
    self.backlog_sync_state = QLabel("Backlog ready")
    self.backlog_sync_state.setObjectName("muted")
    self.backlog_sync_state.setWordWrap(True)
    backlog_layout.addWidget(self.backlog_sync_state)
    backlog_layout.addWidget(QLabel("Backlog status"))
    status_row = QHBoxLayout()
    self.status = QComboBox()
    self.apply_status = QPushButton("Update")
    self.apply_status.setToolTip("Update the selected ticket status in Backlog")
    status_row.addWidget(self.status, 1)
    status_row.addWidget(self.apply_status)
    backlog_layout.addLayout(status_row)
    backlog_layout.addWidget(QLabel("Ticket comment"))
    self.comment = QTextEdit()
    self.comment.setPlaceholderText("Write a Backlog comment, or generate a Japanese draft from this ticket’s SVN patch…")
    self.comment.setMinimumHeight(118)
    self.comment.setAcceptRichText(False)
    backlog_layout.addWidget(self.comment, 1)
    self.ai_comment = QPushButton("AI Generate Ticket Comment")
    self.ai_comment.setObjectName("aiCommentButton")
    self.ai_comment.setProperty("secondary", True)
    self.ai_comment.setToolTip("Draft the fixed Japanese comment template from this ticket's verified SVN patch and llama.cpp")
    backlog_layout.addWidget(self.ai_comment)
    self.add_comment = QPushButton("Post comment")
    self.add_comment.setToolTip("Review and post a Backlog comment (Ctrl+Shift+C)")
    backlog_layout.addWidget(self.add_comment)
    self.open_ticket = QPushButton("Open ticket in Backlog")
    self.open_ticket.setProperty("secondary", True)
    backlog_layout.addWidget(self.open_ticket)

    context_tab = QWidget()
    context_tab.setObjectName("inspectorTab")
    context_layout = QVBoxLayout(context_tab)
    context_layout.setContentsMargins(7, 7, 7, 7)
    context_layout.setSpacing(4)
    context_layout.addWidget(QLabel("Description"))
    self.description = QTextEdit()
    self.description.setReadOnly(True)
    self.description.setAcceptRichText(False)
    self.description.setMinimumHeight(94)
    context_layout.addWidget(self.description, 1)
    context_layout.addWidget(QLabel("Local workflow"))
    self.local_workflow = QComboBox()
    self.local_workflow.addItems(["Untriaged", "Waiting on me", "Waiting on someone else", "Blocked", "Ready to test", "Ready to release"])
    self.local_workflow.setToolTip("Local workflow state; does not change Backlog")
    context_layout.addWidget(self.local_workflow)
    context_layout.addWidget(QLabel("Related tickets"))
    self.related_input = QLineEdit()
    self.related_input.setPlaceholderText("Ticket keys, comma separated")
    context_layout.addWidget(self.related_input)
    self.save_context = QPushButton("Save local context")
    self.save_context.setProperty("secondary", True)
    context_layout.addWidget(self.save_context)
    personal_row = QHBoxLayout()
    self.my_day = QPushButton("My Day")
    self.my_day.setProperty("secondary", True)
    self.my_day.setToolTip("Add or remove this ticket from My Day (Ctrl+Shift+M)")
    self.reminder = QPushButton("Remind")
    self.reminder.setProperty("secondary", True)
    self.favorite = QPushButton("☆ Star")
    self.favorite.setProperty("secondary", True)
    personal_row.addWidget(self.my_day)
    personal_row.addWidget(self.reminder)
    personal_row.addWidget(self.favorite)
    context_layout.addLayout(personal_row)
    self.seen = QPushButton("Mark seen")
    self.seen.setProperty("secondary", True)
    context_layout.addWidget(self.seen)
    context_layout.addWidget(self.reminder_state)

    self.inspector_tabs.addTab(work_tab, "Work")
    self.inspector_tabs.addTab(backlog_tab, "Backlog")
    self.inspector_tabs.addTab(context_tab, "Context")
    layout.addWidget(self.inspector_tabs, 1)
    self.start.clicked.connect(self.start_work)
    self.full_detail.clicked.connect(self.open_ticket_detail)
    self.stop.clicked.connect(self.stop_work)
    self.note.clicked.connect(self.create_note)
    self.my_day.clicked.connect(self.toggle_current_my_day)
    self.reminder.clicked.connect(self.open_reminder_menu)
    self.favorite.clicked.connect(self.toggle_current_favorite)
    self.seen.clicked.connect(self.toggle_current_seen)
    self.open_ticket.clicked.connect(self.open_current_ticket)
    self.source_control_button.clicked.connect(self.open_source_control)
    self.make_patch_button.clicked.connect(lambda: self.open_source_control("create_patch"))
    self.patches_button.clicked.connect(lambda: self.open_source_control("patches"))
    self.environment_button.clicked.connect(lambda: self.open_ticket_environment(self.current) if self.current else None)
    self.apply_status.clicked.connect(self.change_status)
    self.save_context.clicked.connect(self.save_local_context)
    self.ai_comment.clicked.connect(self.generate_inspector_comment)
    self.add_comment.clicked.connect(self.post_comment)
    self.comment.textChanged.connect(self._remember_comment_draft)
    scroll = QScrollArea()
    scroll.setFrameShape(QFrame.Shape.NoFrame)
    scroll.setWidgetResizable(True)
    scroll.setHorizontalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
    scroll.setMinimumWidth(306)
    scroll.setMaximumWidth(420)
    scroll.setWidget(panel)
    return scroll
